name: Lint

on:
    push:
    pull_request:
        types: [opened, synchronize]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                python-version: ["3.10", "3.11"]
        
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
                with:
                    fetch-depth: 0
            
            -   name: Install CPython
                uses: actions/setup-python@v2
                with:
                    python-version: ${{matrix.python-version}}
            
            -   name: Install build dependancies
                run: |
                    python -m ensurepip
                    pip install -U setuptools wheel build
            
            -   name: Install lib
                run: pip install .
            
            -   name: Import check
                uses: jannekem/run-python-script-action@v1
                with:
                    script: |
                        import kickio
                        print(kickio.__version__)
            
            -   name: Build wheel
                run: python -m build

    style:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
                with:
                    fetch-depth: 0
            
            -   name: Install CPython
                uses: actions/setup-python@v2
                with:
                    python-version: 3.11
        
            -   name: Install deps
                run: |
                    python -m ensurepip
                    pip install -U black
            
            -   name: Run black
                run: black kickio --verbose --check

    pyright:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
                with:
                    fetch-depth: 0
            
            -   name: Install NodeJS
                uses: actions/setup-node@v1
                with:
                    node-version: 17
            
            -   name: Run Pyright
                uses: jakebailey/pyright-action@v1
                with:
                    version: 1.1.311
                    warnings: false
                    no-comments: false
    